### ISSUE TITLE
technical.moving_averages: Getting the error at the request for Canada

### ISSUE THREAD

**Issue by guberm** [alvarobartt/investpy#346]
Request: investpy.technical.moving_averages(name='WELL', country='Canada', product_type='stock', interval='daily')

Error: Exception has occurred: AttributeError
'float' object has no attribute 'encode'

** For the United States is working correctly

**Comment by alvarobartt** [comment]
Hi @guberm, thanks for the report, I'll check this now! :fire:

**Comment by guberm** [comment]
I did the update, but still getting the error :-( sorry for that

I'm not sure if that relevant, but you didn't update technical.py and stock.py

![image](https://user-images.githubusercontent.com/577099/114869967-9a6ec180-9dc5-11eb-8644-d081875c0f54.png)

`Traceback (most recent call last):
  File "c:\Users\michael.guber\Desktop\investpy0.py", line 48, in <module>
    techData = get_stock_tech_data(stock_symb, intervalS, type, countryS)
  File "c:\Users\michael.guber\Desktop\investpy0.py", line 40, in get_stock_tech_data
    techData = investpy.technical.moving_averages(name='WELL', country='Canada', product_type='stock', interval='daily')
  File "c:\users\michael.guber\appdata\local\programs\python\python39\lib\site-packages\investpy\technical.py", line 273, in moving_averages
    if name not in list(data[check].apply(unidecode).str.lower()):
  File "c:\users\michael.guber\appdata\local\programs\python\python39\lib\site-packages\pandas-1.2.3-py3.9-win-amd64.egg\pandas\core\series.py", line 4138, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas\_libs\lib.pyx", line 2467, in pandas._libs.lib.map_infer
  File "c:\users\michael.guber\appdata\local\programs\python\python39\lib\site-packages\unidecode-1.2.0-py3.9.egg\unidecode\__init__.py", line 66, in unidecode_expect_ascii
    bytestring = string.encode('ASCII')
AttributeError: 'float' object has no attribute 'encode'`

Thank you for your work
