### ISSUE TITLE
Error when importing investpi in Raspberry Pi Zero python3

### ISSUE THREAD

**Issue by wongfred88** [alvarobartt/investpy#531]
hi there
I encountered an error when importing investpi in python3 with Raspberry Pi Zero. Here are the code:
===============
>>> import investpi as inv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/investpy/__init__.py", line 7, in <module>
    from .bonds import (
  File "/usr/local/lib/python3.9/dist-packages/investpy/bonds.py", line 13, in <module>
    from lxml.html import fromstring
  File "/usr/local/lib/python3.9/dist-packages/lxml/html/__init__.py", line 53, in <module>
    from .. import etree
ImportError: libxslt.so.1: cannot open shared object file: No such file or directory
================
I have installed the investpi module using "sudo apt-get install investpy" and the installation is completed.
Any suggestion will be welcome.

**Comment by wongfred88** [comment]
Oh, it works now by installing "sudo apt-get install libxslt-dev", thanks.
