### ISSUE TITLE
403 with USDEUR Data

### ISSUE THREAD

**Issue by Killpit** [alvarobartt/investpy#621]
Hi, I was working with investor currency_crosses function and while I follow the documentation from [here](https://investpy.readthedocs.io/_api/currency_crosses.html) , I just got an 403 error.

`import investpy

data = investpy.get_currency_cross_historical_data(currency_cross='USD/EUR', from_date='01/01/2022', to_date='25/01/2023')
print(data.head())`

After I ran the code, this is the error:

Traceback (most recent call last):
  File "/Users/atatekeli/PycharmProjects/CurrencyPricePredictorAutoTS/USDEUR.py", line 3, in <module>
    data = investpy.get_currency_cross_historical_data(currency_cross='USD/EUR', from_date='01/01/2022', to_date='25/01/2023')
  File "/Users/atatekeli/PycharmProjects/CurrencyPricePredictorAutoTS/venv/lib/python3.9/site-packages/investpy/currency_crosses.py", line 674, in get_currency_cross_historical_data
    raise ConnectionError(
ConnectionError: ERR#0015: error 403, try again later.

**Comment by oguzkirman** [comment]
This library doesn't work after last Investing update.
