### ISSUE TITLE
Not working on Python 3.11

### ISSUE THREAD

**Issue by gi-dellav** [alvarobartt/investpy#640]
Using some workarounds I managed to make the library work just fine on Python 3.10, but I have to develop an extension for a platform using Python 3.11 and on this version every request raises the exception: `ConnectionError: ERR#0015: error 403, try again later.`.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/dist-packages/investpy/search.py", line 160, in search_quotes
    raise ConnectionError(
ConnectionError: ERR#0015: error 403, try again later.
```

Any way to resolve this issue?

Thanks in advance.

**Comment by raccoonpesfifa** [comment]
anyone helping with this issue? i experience the same...
